### ISSUE TITLE
OMV dependencies broken

### ISSUE THREAD

**Issue by venhyy** [armbian/config#13]
Cant install OMV right now, I installed today for the first time, then erase SD card and cant install it again. 
There are issues with dependencies with OMV and omv-extras.

**Comment by ThomasKaiser** [comment]
This happens from time to time when upstream repository changes are made (which happens quite often with OMV 4 these days). Since you did not provide any information (most importantly which OMV version) and I installed OMV more than 10 times within the last 24 hours with `softy` it can be assumed that if there was an issue it's fixed now.
